---
- name: Stop Kibana service
  shell: systemctl stop kibana

- name: Uninstall keycloak-kibana plugin (if present)
  shell: sudo /usr/share/kibana/bin/kibana-plugin remove --allow-root keycloak-kibana
  failed_when: false
  changed_when: false

- name: Include keycloak.serverUrl attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.serverUrl: http://{{keycloak_ip_address}}:8080/auth"
    insertafter: EOF

- name: Include keycloak.realm attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.realm: {{keycloak_realm}}"
    insertafter: EOF

- name: Include keycloak.clientId attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.clientId: {{keycloak_client}}"
    insertafter: EOF

- name: Include keycloak.clientSecret attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.clientSecret: {{keycloak_clientsecret}}"
    insertafter: EOF

- name: Include keycloak.acl.enabled attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.acl.enabled: true"
    insertafter: EOF

- name: Include keycloak.session.cookieOptions.password attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.session.cookieOptions.password: {{keycloak_cookie_password}}"
    insertafter: EOF

- name: Include keycloak.session.cookieOptions.isSecure in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.session.cookieOptions.isSecure: false"
    insertafter: EOF

- name: Include keycloak.principalNameAttribute attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.principalNameAttribute: preferred_username"
    insertafter: EOF

- name: Include keycloak.acl.ownerAttribute attribute in Kibana configuration file
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "keycloak.acl.ownerAttribute: preferred_username"
    insertafter: EOF

- name: Install keycloak-kibana plugin
  shell: sudo /usr/share/kibana/bin/kibana-plugin install --allow-root https://github.com/novomatic-tech/keycloak-kibana/releases/download/3.2.1/keycloak-kibana-3.2.1_7.5.0.zip

- name: Start Kibana service
  shell: systemctl start kibana

- name: Press enter to continue
  pause: prompt='Press enter to continue'
  when: prompt_when_finishes_tasks
